name = "nick-site"
compatibility_date = "2026-04-14"
pages_build_output_dir = "./dist"

[[queues.producers]]
binding = "NCS_CONTROL_QUEUE"
queue = "ncs-control-queue"

[[analytics_engine_datasets]]
binding = "WORKER_ANALYTICS"
dataset = "nick_site_usage_metrics"
